name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Test
      run: ./Day1/Debug/*.exe
      timeout-minutes: 1
